# Generated by Django 2.2.4 on 2023-01-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KakaoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('alarm_0_0', models.BooleanField(default=False)),
                ('alarm_1_0', models.BooleanField(default=False)),
                ('alarm_2_0', models.BooleanField(default=False)),
                ('alarm_3_0', models.BooleanField(default=False)),
                ('alarm_4_0', models.BooleanField(default=False)),
                ('alarm_0_1', models.BooleanField(default=False)),
                ('alarm_1_1', models.BooleanField(default=False)),
                ('alarm_2_1', models.BooleanField(default=False)),
                ('alarm_3_1', models.BooleanField(default=False)),
                ('alarm_4_1', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price0', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price1', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DELNG_DE', models.CharField(max_length=30)),
                ('MRKT_NM', models.CharField(max_length=30)),
                ('CPR_NM', models.CharField(max_length=30)),
                ('PRDLST_NM', models.CharField(max_length=30)),
                ('SPCIES_NM', models.CharField(max_length=30)),
                ('GRAD', models.CharField(max_length=30)),
                ('weight', models.CharField(max_length=30)),
                ('PRI_MAX', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PRI_MIN', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PRI_AVE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PRI_PRED', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
